---
- name: Create .zshenv file
  include_tasks: "zshenv.yml"

- name: Create SSH directories
  include_tasks: "create_ssh_directories.yml"
  when: ssh_origins is defined and ssh_origins | length > 0

- name: Create SSH keys
  include_tasks: "ssh_keys.yml"
  when: ssh_origins is defined and ssh_origins | length > 0

- name: Add SSH keys to env
  include_tasks: "ssh_add.yml"
  when: ssh_origins is defined and ssh_origins | length > 0
