- name: Install and configure Node.js development tools
  block:
    - name: Check if Node.js is installed
      command: which node
      register: node_check
      ignore_errors: true

    - name: Add nodejs plugin to asdf
      command: asdf plugin-add nodejs
      when: node_check.rc != 0
      ignore_errors: true

    - name: Install nodejs lts with asdf
      command: asdf install nodejs 18.12.0
      when: node_check.rc != 0

    - name: Set nodejs lts as the global version with asdf
      command: asdf global nodejs lts
      when: node_check.rc != 0

    - name: Install neovim with npm
      command: npm i -g neovim
      when: node_check.rc != 0

    - name: Install prettier with npm
      command: npm install -g prettier
      when: node_check.rc != 0

