- name: Install and configure Python development tools
  block:
    - name: Check if Python 3.11.0 is installed
      command: python3.11 --version
      register: python_check
      ignore_errors: true

    - name: Add python plugin to asdf
      command: asdf plugin-add python
      when: python_check.rc != 0

    - name: Install python 3.11.0 with asdf
      command: asdf install python 3.11.0
      when: python_check.rc != 0

    - name: Set python 3.11.0 as the global version with asdf
      command: asdf global python 3.11.0
      when: python_check.rc != 0

    - name: Install pynvim with pip
      command: pip3 install pynvim
      when: python_check.rc != 0
