---
- name: Install and configure Rust development tools
  block:
    - name: Add Rust plugin to asdf
      command: asdf plugin-add rust
    - name: Install Rust stable with asdf
      command: asdf install rust stable
    - name: Set Rust stable as the global version with asdf
      command: asdf global rust stable
    - name: Install rust tools
      command: rustup default stable
