alias k='kubectl'
alias kga='kubectl get all'
alias kgaa='kubectl get all --all-namespaces'
alias kgp='kubectl get pods'
alias kgpa='kubectl get pods --all-namespaces'
alias kgs='kubectl get services'
alias kgd='kubectl get deployments'
alias kgn='kubectl get nodes'
alias kgc='kubectl get configmaps'
alias kgi='kubectl get ingress'
alias kgr='kubectl get replicasets'
alias kgrs='kubectl get rs'
alias kgnp='kubectl get networkpolicies'
alias kgnpa='kubectl get networkpolicies --all-namespaces'
alias kgnr='kubectl get namespaces'

alias kd='kubectl describe'
alias kdp='kubectl describe pods'
alias kds='kubectl describe services'
alias kdd='kubectl describe deployments'
alias kdn='kubectl describe nodes'
alias kdc='kubectl describe configmaps'
alias kdi='kubectl describe ingress'
alias kdr='kubectl describe replicasets'
alias kdr='kubectl describe rs'
alias kdnr='kubectl describe namespaces'

alias krm='kubectl delete'
alias krmp='kubectl delete pods'
alias krms='kubectl delete services'
alias krmd='kubectl delete deployments'
alias krmi='kubectl delete ingress'
alias krmp='kubectl delete pods'
alias krms='kubectl delete services'
alias krmd='kubectl delete deployments'
alias krmi='kubectl delete ingress'
alias krmc='kubectl delete configmaps'
alias krmr='kubectl delete replicasets'
alias krmr='kubectl delete rs'

alias kaf='kubectl apply -f'

alias kl='kubectl logs'


alias kcc='kubectl config current-context'
alias kcg='kubectl config get-contexts'
alias kcs='kubectl config set-context'
alias kcu='kubectl config use-context'
