alias safari='open /Applications/Safari.app'
alias sim='open -a Simulator'
alias edge='open -a "Microsoft Edge" '
alias chrome='open -a "Google Chrome" '
alias excel='open -a "Microsoft Excel" '
alias word='open -a "Microsoft Word" '
alias powerpoint='open -a "Microsoft PowerPoint" '
alias outlook='open -a "Microsoft Outlook" '
