---
brewfile_location: ~/dotfiles/brew/Brewfile.linux
zdotdir: ~/dotfiles/zsh
ssh_origins:
  - {name: Github, hostname: github.com, user: git, identityfile: ~/.ssh/github/github,
    location: ~/.ssh/github, primary: true}
  - {name: DevOps, hostname: dev.azure.com, user: git, identityfile: ~/.ssh/devops/devops,
    location: ~/.ssh/devops, primary: true}
  - {name: SSHDevOps, hostname: ssh.dev.azure.com, user: git,
    identityfile: ~/.ssh/sshdevops/sshdevops, location: ~/.ssh/sshdevops, primary: true}
  - {name: GithubSensey, hostname: github.com, user: git, identityfile: ~/.ssh/github-sensey/github-sensey,
    location: ~/.ssh/github-sensey, primary: false, orgs: [senseylabs]}
stow_directories: [git, config, asdf]
