live_config_reload = true

[env]
term = "xterm-256color"

[window]
startup_mode = "Maximized"
option_as_alt = "Both"
decorations = "Buttonless"


[font]
# Normal (Regular) font face
normal = { family = "MesloLGL Nerd Font" }

# Bold font face
bold = { family = "MesloLGL Nerd Font" }

# Italic font face
italic = { family = "MesloLGL Nerd Font" }

# Bold Italic font face
bold_italic = { family = "MesloLGL Nerd Font" }

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.selection]
text = "CellForeground"
background = "#4c566a"

[colors.search.matches]
foreground = "CellBackground"
background = "#88c0d0"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[colors.dim]
black = "#373e4d"
red = "#94545d"
green = "#809575"
yellow = "#b29e75"
blue = "#68809a"
magenta = "#8c738c"
cyan = "#6d96a5"
white = "#aeb3bb"


# Window/Pane management
[[keyboard.bindings]]
key = "T"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["new-window", "-c", "#{pane_current_path}"] }

[[keyboard.bindings]]
key = "W"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["kill-pane"] }

# [[keyboard.bindings]]
# key = "D"
# mods = "Command"
# command = { program = "/opt/homebrew/bin/tmux", args = ["kill-pane"] }

[[keyboard.bindings]]
key = "J"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["split-window", "-v", "-c", "#{pane_current_path}"] }

[[keyboard.bindings]]
key = "K"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["split-window", "-h", "-c", "#{pane_current_path}"] }

[[keyboard.bindings]]
key = "I"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["send-keys", "C-l"] }

# Session management (switching)
[[keyboard.bindings]]
key = "S"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["choose-tree", "-s", "-O", "name", "-ZsK", "#{?#{e|<:#{line},9},#{e|+:1,#{line}},#{?#{e|<:#{line},35},M-#{a:#{e|+:97,#{e|-:#{line},9}}},}}", ";"] }

# Move windows
[[keyboard.bindings]]
key = "P"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["swap-window", "-t", "-1", ";", "select-window", "-t", "-1"] }

[[keyboard.bindings]]
key = "N"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["swap-window", "-t", "+1", ";", "select-window", "-t", "+1"] }

[[keyboard.bindings]]
key = "f"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["copy-mode"] }
  
# Switch to window by number
[[keyboard.bindings]]
key = "1"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":1"] }

[[keyboard.bindings]]
key = "2"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":2"] }

[[keyboard.bindings]]
key = "3"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":3"] }

[[keyboard.bindings]]
key = "4"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":4"] }

[[keyboard.bindings]]
key = "5"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":5"] }

[[keyboard.bindings]]
key = "6"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":6"] }

[[keyboard.bindings]]
key = "7"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":7"] }

[[keyboard.bindings]]
key = "8"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":8"] }

[[keyboard.bindings]]
key = "9"
mods = "Command"
command = { program = "/opt/homebrew/bin/tmux", args = ["select-window", "-t", ":9"] }
